package: tasktracker
generate:
  chi-server: true
  client: true
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
  disable-type-aliases-for-type: []
output: api/openapi.gen.go
