# oapi-codegen -config api/code-gen-configs/server/project.yaml api/openapi/server/project.yaml
package: api
generate:
  chi-server: true
  # strict-server: true
  # client: true
  # models: true
  # embedded-spec: true
output-options:
  skip-prune: true
  disable-type-aliases-for-type: []
import-mapping:
  ../schema.yaml: github.com/AgamBenItzhak/TaskTracker/api
output: api/services/project/openapi.project.gen.go
