openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
paths:
  /auth/refresh:
    post:
      summary: Refresh a member's token
      operationId: RefreshMemberToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/auth.yaml#/components/schemas/token_refresh_request'
      responses:
        '200':
          description: The member's new token
          content:
            application/json:
              schema:
                $ref: '../schemas/auth.yaml#/components/schemas/token_refresh_response'