openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
paths:
  /auth/login:
    post:
      summary: Log in a member
      operationId: loginMember
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/auth.yaml#/components/schemas/login_request'
      responses:
        '200':
          description: The member's token
          content:
            application/json:
              schema:
                $ref: '../schemas/auth.yaml#/components/schemas/login_response'
  /auth/logout:
    post:
      summary: Log out a member
      operationId: logoutMember
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/auth.yaml#/components/schemas/logout_request'
      responses:
        '204':
          description: The member has been logged out
          content:
            application/json:
              schema:
                $ref: '../schemas/auth.yaml#/components/schemas/logout_response'
  /auth/refresh:
    post:
      summary: Refresh a member's token
      operationId: refreshMemberToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/auth.yaml#/components/schemas/token_refresh_request'
      responses:
        '200':
          description: The member's new token
          content:
            application/json:
              schema:
                $ref: '../schemas/auth.yaml#/components/schemas/token_refresh_response'
  /auth/password/reset:
    post:
      summary: Reset a member's password
      operationId: updateMemberCredentialsByID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/auth.yaml#/components/schemas/member_credentials_update_request'
      responses:
        '204':
          description: The member's password has been reset
          content:
            application/json:
              schema:
                $ref: '../schemas/auth.yaml#/components/schemas/member_credentials_update_response'
        '404':
          description: The member does not exist