openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
paths:
  /project:
    get:
      summary: Get all projects
      operationId: getAllProjects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/project.yaml#/components/schemas/project'
    post:
      summary: Create a new project
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/project.yaml#/components/schemas/project'
      responses:
        '201':
          description: The newly created project
          content:
            application/json:
              schema:
                $ref: '../schemas/project.yaml#/components/schemas/project'
  /project/{project_id}:
    get:
      summary: Get a project by ID
      operationId: getProjectByID
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to get
          schema:
            type: integer
      responses:
        '200':
          description: The project with the specified ID
          content:
            application/json:
              schema:
                $ref: '../schemas/project.yaml#/components/schemas/project'
    put:
      summary: Update a project by ID
      operationId: updateProjectByID
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/project.yaml#/components/schemas/project'
      responses:
        '200':
          description: The updated project
          content:
            application/json:
              schema:
                $ref: '../schemas/project.yaml#/components/schemas/project'
        '404':
          description: 'Project not found'
    delete:
      summary: Delete a project by ID
      operationId: deleteProjectByID
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to delete
          schema:
            type: integer
      responses:
        '204':
          description: 'Project deleted successfully'
        '404':
          description: 'Project not found'
    patch:
      summary: Partially update a project by ID
      operationId: patchProjectByID
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/project.yaml#/components/schemas/project'
      responses:
        '200':
          description: The updated project
          content:
            application/json:
              schema:
                $ref: '../schemas/project.yaml#/components/schemas/project'
        '404':
          description: 'Project not found'
  /project/{project_id}/tasks:
    get:
      summary: Get all tasks for a project
      operationId: getAllTasksForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to get tasks for
          schema:
            type: integer
      responses:
        '200':
          description: A list of tasks for the project
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/task.yaml#/components/schemas/task'
    post:
      summary: Create a new task for a project
      operationId: createTaskForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to create a task for
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/task.yaml#/components/schemas/task'
      responses:
        '201':
          description: The newly created task
          content:
            application/json:
              schema:
                $ref: '../schemas/task.yaml#/components/schemas/task'
  /project/{project_id}/tasks/{task_id}:
    get:
      summary: Get a task by ID for a project
      operationId: getTaskByIDForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to get the task for
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to get
          schema:
            type: integer
      responses:
        '200':
          description: The task with the specified ID
          content:
            application/json:
              schema:
                $ref: '../schemas/task.yaml#/components/schemas/task'
    put:
      summary: Update a task by ID for a project
      operationId: updateTaskByIDForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to update the task for
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/task.yaml#/components/schemas/task'
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '../schemas/task.yaml#/components/schemas/task'
        '404':
          description: 'Task not found'
    delete:
      summary: Delete a task by ID for a project
      operationId: deleteTaskByIDForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to delete the task for
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
      responses:
        '204':
          description: 'Task deleted successfully'
        '404':
          description: 'Task not found'
    patch:
      summary: Partially update a task by ID for a project
      operationId: patchTaskByIDForProject
      parameters:
        - name: project_id
          in: path
          required: true
          description: The ID of the project to update the task for
          schema:
            type: integer
        - name: task_id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/task.yaml#/components/schemas/task'
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '../schemas/task.yaml#/components/schemas/task'
        '404':
          description: 'Task not found'