openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
paths:
  /projects:
    get:
      summary: Get all projects
      description: Get all projects in the system.
      tags:
        - projects
      responses:
        '200':
          description: Projects found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schema.yaml#/components/schemas/project'
        '404':
          description: Projects not found
    post:
      summary: Create a new project
      description: Create a new project in the system.
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/project'
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/project'
        '400':
          description: Invalid input
  /projects/{project_id}:
    get:
      summary: Get project by ID
      description: Get a project by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Project found
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/project'
        '404':
          description: Project not found
    put:
      summary: Update project by ID
      description: Update a project by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/project'
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/project'
        '404':
          description: Project not found
    delete:
      summary: Delete project by ID
      description: Delete a project by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Project deleted
        '404':
          description: Project not found
  /projects/{project_id}/users:
    get:
      summary: Get all users in project
      description: Get all users in a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get users from
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schema.yaml#/components/schemas/user'
        '404':
          description: Users not found
    post:
      summary: Add user to project
      description: Add a user to a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to add user to
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/project_user'
      responses:
        '201':
          description: User added to project
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/project_user'
        '400':
          description: Invalid input
  /projects/{project_id}/users/{user_id}:
    put:
      summary: Update user role in project
      description: Update a user's role in a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to update user role in
          schema:
            type: integer
            format: int64
        - name: user_id
          in: path
          required: true
          description: ID of the user to update role for
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/project_user'
      responses:
        '200':
          description: User role updated
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/project_user'
        '404':
          description: User or project not found
    delete:
      summary: Remove user from project
      description: Remove a user from a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to remove user from
          schema:
            type: integer
            format: int64
        - name: user_id
          in: path
          required: true
          description: ID of the user to remove from project
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User removed from project
        '404':
          description: User or project not found
  /projects/{project_id}/task-groups:
    get:
      summary: Get all task groups in project
      description: Get all task groups in a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get task groups from
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Task groups found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schema.yaml#/components/schemas/task_group'
        '404':
          description: Task groups not found
    post:
      summary: Create a new task group in project
      description: Create a new task group in a project.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to create task group in
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/task_group'
      responses:
        '201':
          description: Task group created
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task_group'
        '400':
          description: Invalid input
  /projects/{project_id}/task-groups/{task_group_id}:
    get:
      summary: Get task group by ID
      description: Get a task group by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get task group from
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Task group found
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task_group'
        '404':
          description: Task group not found
    put:
      summary: Update task group by ID
      description: Update a task group by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to update task group in
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/task_group'
      responses:
        '200':
          description: Task group updated
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task_group'
        '404':
          description: Task group not found
    delete:
      summary: Delete task group by ID
      description: Delete a task group by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to delete task group from
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Task group deleted
  /projects/{project_id}/task-groups/{task_group_id}/tasks:
    get:
      summary: Get all tasks in task group
      description: Get all tasks in a task group.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get tasks from
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to get tasks from
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tasks found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schema.yaml#/components/schemas/task'
        '404':
          description: Tasks not found
    post:
      summary: Create a new task in task group
      description: Create a new task in a task group.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to create task in
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to create task in
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/task'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task'
        '400':
          description: Invalid input
  /projects/{project_id}/task-groups/{task_group_id}/tasks/{task_id}:
    get:
      summary: Get task by ID
      description: Get a task by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to get task from
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to get task from
          schema:
            type: integer
            format: int64
        - name: task_id
          in: path
          required: true
          description: ID of the task to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task'
        '404':
          description: Task not found
    put:
      summary: Update task by ID
      description: Update a task by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to update task in
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to update task in
          schema:
            type: integer
            format: int64
        - name: task_id
          in: path
          required: true
          description: ID of the task to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/task'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/task'
        '404':
          description: Task not found
    delete:
      summary: Delete task by ID
      description: Delete a task by its ID.
      tags:
        - projects
      parameters:
        - name: project_id
          in: path
          required: true
          description: ID of the project to delete task from
          schema:
            type: integer
            format: int64
        - name: task_group_id
          in: path
          required: true
          description: ID of the task group to delete task from
          schema:
            type: integer
            format: int64
        - name: task_id
          in: path
          required: true
          description: ID of the task to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Task deleted