openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api
paths:
  /users/{user_id}:
    get:
      summary: Get user by ID
      description: Get a user by their ID.
      tags:
        - users
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/user'
        '404':
          description: User not found
    put:
      summary: Update user by ID
      description: Update a user by their ID.
      tags:
        - users
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema.yaml#/components/schemas/user'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '../schema.yaml#/components/schemas/user'
        '404':
          description: User not found
    delete:
      summary: Delete user by ID
      description: Delete a user by their ID.
      tags:
        - users
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found