components:
  schemas:
    project:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        project_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: project_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        status:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: status
        start_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: start_date
        end_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: end_date
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
      required:
        - project_id
        - project_name
        - created_at
        - updated_at
    project_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
      required:
        - project_id
    project_response:
      type: object
      properties:
        project:
          $ref: "#/components/schemas/project"
      required:
        - project
    projects_request:
      type: object
      properties:
        project_ids:
          type: array
          items:
            type: integer
            format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_ids
      required:
        - project_ids
    projects_response:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: "#/components/schemas/project"
          x-oapi-codegen-extra-tags:
            mapstructure: projects
      required:
        - projects
    project_create_request:
      type: object
      properties:
        project_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: project_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        status:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: status
        start_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: start_date
        end_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: end_date
      required:
        - project_name
    project_create_response:
      type: object
      properties:
        project:
          $ref: "#/components/schemas/project"
      required:
        - project
    project_update_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        project_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: project_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        status:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: status
        start_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: start_date
        end_date:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: end_date
      required:
        - project_id
    project_update_response:
      type: object
      properties:
        project:
          $ref: "#/components/schemas/project"
      required:
        - project
    project_delete_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
      required:
        - project_id
    project_delete_response:
      type: object
      properties:
        message:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: message
      required:
        - message
    project_member:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        member_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: member_id
        role:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: role
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
      required:
        - project_id
        - member_id
        - role
        - created_at
        - updated_at
    project_member_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        member_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: member_id
      required:
        - project_id
        - member_id
    project_member_response:
      type: object
      properties:
        project_member:
          $ref: "#/components/schemas/project_member"
      required:
        - project_member
    project_members_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
      required:
        - project_id
    project_members_response:
      type: object
      properties:
        project_members:
          type: array
          items:
            $ref: "#/components/schemas/project_member"
          x-oapi-codegen-extra-tags:
            mapstructure: project_members
      required:
        - project_members
    project_member_create_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        member_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: member_id
        role:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: role
      required:
        - project_id
        - member_id
        - role
    project_member_create_response:
      type: object
      properties:
        project_member:
          $ref: "#/components/schemas/project_member"
      required:
        - project_member
    project_member_update_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        member_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: member_id
        role:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: role
      required:
        - project_id
        - member_id
    project_member_update_response:
      type: object
      properties:
        project_member:
          $ref: "#/components/schemas/project_member"
      required:
        - project_member
    project_member_delete_request:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        member_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: member_id
      required:
        - project_id
        - member_id
    project_member_delete_response:
      type: object
      properties:
        message:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: message
      required:
        - message
