openapi: 3.0.2
info:
  title: TaskTracker API
  description: API for TaskTracker, a project management and task tracking system.
  version: 0.1.0
paths: {}
components:
  schemas:
    error:
      type: object
      properties:
        error:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: error
    user:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: user_id
        email:
          type: string
          format: email
          x-oapi-codegen-extra-tags:
            mapstructure: email
        password:
          type: string
          format: password
          writeOnly: true
          x-oapi-codegen-extra-tags:
            mapstructure: password
        first_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: first_name
        last_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: last_name
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
        last_seen:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: last_seen
    project:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        project_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: project_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        status:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: status
        start_date:
          type: string
          format: date
          x-oapi-codegen-extra-tags:
            mapstructure: start_date
        end_date:
          type: string
          format: date
          x-oapi-codegen-extra-tags:
            mapstructure: end_date
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
    project_user:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: user_id
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        role:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: role
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
    task_group:
      type: object
      properties:
        task_group_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: task_group_id
        project_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: project_id
        group_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: group_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
    task:
      type: object
      properties:
        task_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: task_id
        task_group_id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            mapstructure: task_group_id
        task_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: task_name
        description:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: description
        status:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: status
        priority:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: priority
        start_date:
          type: string
          format: date
          x-oapi-codegen-extra-tags:
            mapstructure: start_date
        end_date:
          type: string
          format: date
          x-oapi-codegen-extra-tags:
            mapstructure: end_date
        created_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: created_at
        updated_at:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            mapstructure: updated_at
    auth_request:
      type: object
      properties:
        email:
          type: string
          format: email
          x-oapi-codegen-extra-tags:
            mapstructure: email
        password:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: password
    auth_response:
      type: object
      properties:
        token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: token
    token:
      type: object
      properties:
        token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: token
    login_request:
      type: object
      properties:
        email:
          type: string
          format: email
          x-oapi-codegen-extra-tags:
            mapstructure: email
        password:
          type: string
          format: password
          x-oapi-codegen-extra-tags:
            mapstructure: password
      required:
        - email
        - password

    login_response:
      type: object
      properties:
        access_token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: access_token
        refresh_token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: refresh_token
        token_type:
          type: string
          default: "Bearer"
          x-oapi-codegen-extra-tags:
            mapstructure: token_type
        expires_in:
          type: integer
          format: int32
          x-oapi-codegen-extra-tags:
            mapstructure: expires_in
      required:
        - access_token
        - token_type
        - expires_in

    logout_response:
      type: object
      properties:
        message:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: message
      required:
        - message
    RegisterUser:
      type: object
      properties:
        email:
          type: string
          format: email
          x-oapi-codegen-extra-tags:
            mapstructure: email
        password:
          type: string
          format: password
          x-oapi-codegen-extra-tags:
            mapstructure: password
        first_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: first_name
        last_name:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: last_name
      required:
        - email
        - password
        - first_name
        - last_name

    password_change_request:
      type: object
      properties:
        current_password:
          type: string
          format: password
          x-oapi-codegen-extra-tags:
            mapstructure: current_password
        new_password:
          type: string
          format: password
          x-oapi-codegen-extra-tags:
            mapstructure: new_password
      required:
        - current_password
        - new_password
    password_change_response:
      type: object
      properties:
        message:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: message
      required:
        - message

    refresh_token_request:
      type: object
      properties:
        refresh_token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: refresh_token
      required:
        - refresh_token

    refresh_token_response:
      type: object
      properties:
        access_token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: access_token
        refresh_token:
          type: string
          x-oapi-codegen-extra-tags:
            mapstructure: refresh_token
        token_type:
          type: string
          default: "Bearer"
          x-oapi-codegen-extra-tags:
            mapstructure: token_type
        expires_in:
          type: integer
          format: int32
          x-oapi-codegen-extra-tags:
            mapstructure: expires_in
      required:
        - access_token
        - token_type
        - expires_in


  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
