# Server Configuration
server:
  address: localhost
  PORT: 5000

# Database Configuration
db:
  host: localhost
  port: 27017
  member: root
  password: root
  dbname: test
  sslmode: disable

#  Logging Configuration
logger:
  level: debug

#  JWT Configuration
jwt:
  secret: secret
  expiration: 3600