// Package member provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package member

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/AgamBenItzhak/TaskTracker/api/schemas/auth"
	externalRef1 "github.com/AgamBenItzhak/TaskTracker/api/schemas/errors"
	externalRef2 "github.com/AgamBenItzhak/TaskTracker/api/schemas/member"
	externalRef3 "github.com/AgamBenItzhak/TaskTracker/api/schemas/project"
	externalRef4 "github.com/AgamBenItzhak/TaskTracker/api/schemas/task"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = externalRef2.MemberCreateRequest

// LoginMemberJSONRequestBody defines body for LoginMember for application/json ContentType.
type LoginMemberJSONRequestBody = externalRef2.LoginRequest

// LogoutMemberJSONRequestBody defines body for LogoutMember for application/json ContentType.
type LogoutMemberJSONRequestBody = externalRef2.LogoutRequest

// UpdateMemberByIDJSONRequestBody defines body for UpdateMemberByID for application/json ContentType.
type UpdateMemberByIDJSONRequestBody = externalRef2.MemberUpdateRequest

// UpdateMemberCredentialsByIDJSONRequestBody defines body for UpdateMemberCredentialsByID for application/json ContentType.
type UpdateMemberCredentialsByIDJSONRequestBody = externalRef2.MemberCredentialsUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all members
	// (GET /member)
	GetAllMembers(w http.ResponseWriter, r *http.Request)
	// Create a new member
	// (POST /member)
	CreateMember(w http.ResponseWriter, r *http.Request)
	// Log in a member
	// (POST /member/login)
	LoginMember(w http.ResponseWriter, r *http.Request)
	// Log out a member
	// (POST /member/logout)
	LogoutMember(w http.ResponseWriter, r *http.Request)
	// Delete a member by ID
	// (DELETE /member/{member_id})
	DeleteMemberByID(w http.ResponseWriter, r *http.Request, memberId int)
	// Get a member by ID
	// (GET /member/{member_id})
	GetMemberByID(w http.ResponseWriter, r *http.Request, memberId int)
	// Update a member by ID
	// (PUT /member/{member_id})
	UpdateMemberByID(w http.ResponseWriter, r *http.Request, memberId int)
	// Delete a member's credentials by ID
	// (DELETE /member/{member_id}/Credentials)
	DeleteMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int)
	// Get a member's credentials by ID
	// (GET /member/{member_id}/Credentials)
	GetMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int)
	// Update a member's credentials by ID
	// (PUT /member/{member_id}/Credentials)
	UpdateMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all members
// (GET /member)
func (_ Unimplemented) GetAllMembers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new member
// (POST /member)
func (_ Unimplemented) CreateMember(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log in a member
// (POST /member/login)
func (_ Unimplemented) LoginMember(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out a member
// (POST /member/logout)
func (_ Unimplemented) LogoutMember(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a member by ID
// (DELETE /member/{member_id})
func (_ Unimplemented) DeleteMemberByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a member by ID
// (GET /member/{member_id})
func (_ Unimplemented) GetMemberByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a member by ID
// (PUT /member/{member_id})
func (_ Unimplemented) UpdateMemberByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a member's credentials by ID
// (DELETE /member/{member_id}/Credentials)
func (_ Unimplemented) DeleteMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a member's credentials by ID
// (GET /member/{member_id}/Credentials)
func (_ Unimplemented) GetMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a member's credentials by ID
// (PUT /member/{member_id}/Credentials)
func (_ Unimplemented) UpdateMemberCredentialsByID(w http.ResponseWriter, r *http.Request, memberId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAllMembers operation middleware
func (siw *ServerInterfaceWrapper) GetAllMembers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllMembers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LoginMember operation middleware
func (siw *ServerInterfaceWrapper) LoginMember(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// LogoutMember operation middleware
func (siw *ServerInterfaceWrapper) LogoutMember(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteMemberByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemberByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMemberByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMemberByID operation middleware
func (siw *ServerInterfaceWrapper) GetMemberByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemberByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateMemberByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateMemberByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMemberByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteMemberCredentialsByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteMemberCredentialsByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMemberCredentialsByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMemberCredentialsByID operation middleware
func (siw *ServerInterfaceWrapper) GetMemberCredentialsByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMemberCredentialsByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// UpdateMemberCredentialsByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateMemberCredentialsByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "member_id" -------------
	var memberId int

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", chi.URLParam(r, "member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMemberCredentialsByID(w, r, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/member", wrapper.GetAllMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/member", wrapper.CreateMember)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/member/login", wrapper.LoginMember)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/member/logout", wrapper.LogoutMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/member/{member_id}", wrapper.DeleteMemberByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/member/{member_id}", wrapper.GetMemberByID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/member/{member_id}", wrapper.UpdateMemberByID)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/member/{member_id}/Credentials", wrapper.DeleteMemberCredentialsByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/member/{member_id}/Credentials", wrapper.GetMemberCredentialsByID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/member/{member_id}/Credentials", wrapper.UpdateMemberCredentialsByID)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yYzW7bOBCAX4XgLtCLYqndYlHoljbAwkAX20P2VAQGI41lNhSpJUdNhUDvviDp6MeS",
	"/FPbcQ+52RQ5M/xmODPkE01UXigJEg2Nn6hJVpAz91OojMuFhv9KMGgHCq0K0MjBfc4hvwe94Kn9s1Q6",
	"Z0hjyiX++Z4GFKsC/F/IQNOA/rhSrOBXiUohA3kFP1CzK2SZl8UKg7pMsNR2VSu6rgNaMGMelXZ61mIN",
	"ai6zA6U2cmor1e6La0hp/LWjr6PtrtmEuv8GCdI6aJCYQkkDQyYalhrMaoHqAaQd+F3Dksb0t7ClHK4R",
	"h35SHdBDZm9Y7keDDcUTpqsSL+7OSfJbbZ7i/Ssa7b8ObU00MIR0wbBnbMoQrpDn0Br8U9HdEW/thZxx",
	"0VPkR45T4mVY+UuuDS4ky+HYY9mRZAULdiK5raC68coLZKuySM/p5o74rWns2dsdul22QTdeekZPh/TC",
	"L5lOIa8x14+5buFqkDSDQyqPmiP8I0VFY9QlnKq67QyFrSVv0/fbU/GuKraeNR65O/SnIJEzYS5fD36p",
	"nmQEkD/Or63bCKaLBfAun7wmz4sU7J8vofv4+qVjrblJ9NU1w8e45/kCMnoDGRpj53G5VFZSCibRvECu",
	"JI3p9Zc5WSpNbpl5uNUseQAdEEYKrexKkjPJMshBImEyJcjMA0E7jcuMmMog5DMbARyF1deRQq6/zGlA",
	"v4M2XlM0ezuLLBdVgGQFpzH9YxbN3rlcgSu3y7D1RQbuXFpyzNo6T2lM/wK8FuJvN8m4m5Z3qlv8Lopc",
	"a68kgnSLWVEInrjl4TejZHuntr84Qm72c3sbPXXDlmnNKo92AykR3CBRS5KvDbVzTJnnTFd+E4QJ0X4N",
	"aKHMyG4/uTLvd0u9o8HgR5VWB+1zj+1tNJMbcWX7n3oA++3ZjHhGPUR7uwIi4VFUZN0xk86xbAl7cITZ",
	"ud0Za02hezlwJ3OU+2f7+azY+685e+GOTq58O2aP6o0h7VtHC/izygiXhE3AVSVupatKPDfe7vPKXnzf",
	"n177PoDJihlyDyCJUFkGKbHshrBVieO0n5oiWfvkLgBhCP3GjXvoH6v5jUu6muWANgPFX59GDJzf2ByG",
	"ramoyFq+rSauE8QVDajvN3rluk876JDbaBbq+m7cFX171hZ49SkxZZKAMctSiGqDlt9pA4vcV2R+Y3Ps",
	"VEE5HoqVfF4i0alz7Z7B+chx5TZrCkj4kkPqYA7L2YB2UY7Q/te1YscD9y3d6Zmfrb5u3DdeOOFPNMIT",
	"rl8/P41XVu/Bgb/HE1L4qb0G75ucOkuOz1Okcw+3Xe7F8lbXjsNz2BvTE7BnRjsRyQzwhTFGZ2gsh89V",
	"u9qe7p4PTYNTDtuZFE/kM3+Ez++2c95Hpt7PLpM7DwmhfgLtx8L2dDoeN24J6O/PMVBqQWO6QiziMBQq",
	"YWKlDMYfog9RaO/V9V39fwAAAP//auNaO0keAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../schemas/auth.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(pathPrefix, "../schemas/errors.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(pathPrefix, "../schemas/member.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(pathPrefix, "../schemas/project.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(pathPrefix, "../schemas/task.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
